<a href="https://colab.research.google.com/github/lmoroney/dlaicourse/blob/master/Hello_World_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### Copyright 2019 The TensorFlow Authors.

In [2]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [7]:
import tensorflow as tf
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers

<!-- model with one layer and one neuron -->

In [5]:
model = Sequential(Dense(units=1,input_shape=[1]))

In [9]:
model =Sequential(Dense(units=1,input_shape=[1]))
model.compile(loss='mean_squared_error',optimizer='sgd')


In [ ]:
x=

In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers

# layer_0 = keras.layers.Dense(units=1, input_shape=[1])
# model = tf.keras.Sequential([layer_0])

# model.compile(optimizer='sgd', loss='mean_squared_error')

# xs = np.array([-1.0,  0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
# ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

# model.fit(xs, ys, epochs=500)

# print(model.predict([10.0]))

# print("Layer variables look like this: {}".format(layer_0.get_weights()))


In [31]:
Y =np.arange(1000)

In [32]:
X = np.square(X)

In [33]:
# define the keras model
model = tf.keras.Sequential()
model.add(keras.layers.Dense(6, input_dim=1, activation='relu'))
model.add(keras.layers.Dense(10, activation='relu'))
model.add(keras.layers.Dense(1))

In [34]:

# compile the keras model
opt = tf.keras.optimizers.Adam(lr=0.001)
model.compile(loss='mean_squared_error', optimizer=opt)

# fit the keras model on the dataset (CPU)
model.fit(X, Y, epochs=100, batch_size=10, verbose=0)


In [35]:
# evaluate the keras model
accuracy = model.evaluate(X, Y, verbose=0)
print('Accuracy: %.2f' % (accuracy))

Accuracy: 147051.19


In [36]:

# make class predictions with the model
predicitions = model.predict(X)

# summarize the first 10 cases
for i in range(10):
    print('%s => %.2f (expected %.2f)' % (X[i].tolist(), predicitions[i], Y[i]))


0 => 1.63 (expected 0.00)
1 => 1.64 (expected 1.00)
4 => 1.99 (expected 2.00)
9 => 2.55 (expected 3.00)
16 => 3.22 (expected 4.00)
25 => 3.24 (expected 5.00)
36 => 3.26 (expected 6.00)
49 => 3.29 (expected 7.00)
64 => 3.32 (expected 8.00)
81 => 3.36 (expected 9.00)


In [12]:
np.linspace(0, 6, num=6)

array([0. , 1.2, 2.4, 3.6, 4.8, 6. ])

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [26]:
xs = np.arange(1.0,7.0)
y=np.arange(1, 4, 0.5)

In [27]:
xs 

array([1., 2., 3., 4., 5., 6.])